[toolchain]
channel = "1.85.0"
components = [
	"cargo",
	"clippy",
	"rustfmt",
	"llvm-tools-preview",
	"rust-analyzer",
	"rust-src",
]
profile = "default"
targets = ["wasm32-unknown-unknown", "wasm32-wasip1"]
