[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[alias]
# bins
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
insta = ["bin", "cargo-insta"]
leptos = ["bin", "cargo-leptos"]
mutants = ["bin", "cargo-mutants"]
tauri = ["bin", "cargo-tauri"]

# tests
test_leptos_cache = [
	"nextest",
	"run",
	"--package",
	"leptos_cache",
]

# this always passes even when it should fail so need to figure it out
test_leptos_testing_library_ = [
	"nextest",
	"run",
	"--test-threads",
	"1",
	"--target",
	"wasm32-unknown-unknown",
	"--package",
	"leptos_testing_library",
]
# tests
test_leptos_testing_library = [
	"test",
	"--target",
	"wasm32-unknown-unknown",
	"--package",
	"leptos_testing_library",
]
