name: "ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  checks:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup development environment
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - name: install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt
        shell: bash

      - name: build
        run: build:all

      - name: lint
        run: lint:all

      - name: test leptos_cache
        run: cargo test_leptos_cache

      - name: test docs
        run: cargo test --doc

      - name: chromedriver test leptos_testing_library
        run: CHROMEDRIVER=$DEVENV_DOTFILE/profile/bin/chromedriver cargo test_leptos_testing_library
        shell: bash

      - name: geckodriver test leptos_testing_library
        run: GECKODRIVER=$DEVENV_DOTFILE/profile/bin/geckodriver cargo test_leptos_testing_library
        shell: bash
